name: file_compression_plus
description: "A Flutter package for compressing various file types including images and PDFs."
version: 0.0.1
homepage: https://github.com/Tisankan/file_compression_plus
repository: https://github.com/Tisankan/file_compression_plus
issue_tracker: https://github.com/Tisankan/file_compression_plus/issues
documentation: https://github.com/Tisankan/file_compression_plus/blob/main/README.md
topics: [flutter, file-compression, image-compression, pdf-compression, flutter-package, dart, image-processing, pdf-processing, flutter-plugin, file-handling]

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.1.0
  syncfusion_flutter_pdf: ^24.1.47
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  # Empty flutter section
